name: Build

on:
  push:
    branches:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - uses: gradle/wrapper-validation-action@v1.0.5
      - uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build
  publish:
    runs-on: macos-latest
    needs: build
    if: github.ref == 'refs/heads/publish'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: gradle/wrapper-validation-action@v1.0.5
      - uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: publish

env:
  ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
  ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
