name: Build

on:
  push:
    branches:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        jdk: [8, 11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'
      - uses: gradle/wrapper-validation-action@v1.0.5
      - uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build
