name: Coverage
run-name: Upload coverage report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
      - uses: gradle/wrapper-validation-action@v1.0.5
      - uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: koverReport
      - uses: actions/upload-artifact@v3
        with:
          name: kover-report
          path: build/reports/kover/html
      - uses: codecov/codecov-action@v3
        with:
          files: ./build/reports/kover/xml/report.xml
