name: Dokka
run-name: Publish documentation for ${{ github.ref_name }}

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: gradle/wrapper-validation-action@v1.0.5
      - uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: dokkaHtml
      - uses: actions/upload-artifact@v3
        with:
          name: api-documentation
          path: build/dokka
      - run: mkdir -p public/api && cp -r -T build/dokka/ public/api
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: 'public'
      - uses: actions/deploy-pages@v1
        id: deployment
